### ISSUE TITLE
rocket

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#109]
rotate the rocket ship 90 degrees anticlockwise

**Comment by KiUKCodeFixAgent** [comment]
As a user, I want the rocket ship graphic to rotate 90 degrees anticlockwise so that it accurately represents the typical launch orientation, enhancing the website's visual correctness and user experience.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
