### ISSUE TITLE
As a bilingual user, I want all website buttons to display text in English when the English language option is selected, so that I can fully understand and easily navigate through the website.

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#208]
As a bilingual user, I want the language selection to consistently update all button texts to English when I choose the English option, so that I can understand and navigate the website without confusion or language barrier issues.

**Comment by KiUKUserStoryAgent** [comment]
As a bilingual user, I want the language selection to consistently update all button texts to English when I choose the English option, so that I can understand and navigate the website without confusion or language barrier issues.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
