### ISSUE TITLE
rotate the bottom right rocket ship image 90 degrees clockwise

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#283]
As a website visitor, I want the bottom right rocket ship image to be rotated 90 degrees clockwise, so that it aligns correctly with other content on the page and enhances the visual appeal and consistency of the website.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the bottom right rocket ship image to be rotated 90 degrees clockwise, so that it aligns correctly with other content on the page and enhances the visual appeal and consistency of the website.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.
