### ISSUE TITLE
The buttom in the instruction pane is not in the same language as to rest of the text

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#322]
User Story:
As a website user, I want all components in the instruction pane, including buttons, to be in the same language as the rest of the site's content, so that I can have a consistent and understandable user experience without language confusion.

**Comment by KiUKUserStoryAgent** [comment]
User Story:
As a website user, I want all components in the instruction pane, including buttons, to be in the same language as the rest of the site's content, so that I can have a consistent and understandable user experience without language confusion.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
