### ISSUE TITLE
Temperature tab  is not in consisten colour

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#382]

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the temperature tab to have a consistent color so that the information is easy to read and visually harmonious.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
Can we change the tab to button

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the temperature display changed from a tab to a consistently colored button, so that the information is easy to read and the interface looks visually harmonious and user-friendly.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
